### ISSUE TITLE
Notifications from LP for Agent and User messages

### ISSUE THREAD

**Issue by eriesenfeld** [lp-docs-org/link-to-docs#1]
Sequence grows for all, but not for ‘COMPOSING’ and not for ‘ACTIVE’ (sequence is null). It feels like lack of consistency.

Is there a recommendation for best practice to keep track of the sequence ? 

Currently I do the following and it works well for now. Maybe there is an easier way ?
-  I increase my sequence counter every time I get a notification (except ‘COMPOSING and ‘ACTIVE’ as they don’t have a sequence)
- In case I get query JSON result of missed messages, I find the last sequence number and then increase it by one, to make sure I have the next one.

**Comment by eitan101** [comment]
`COMPOSING` and `ACTIVE` are **presence** events which relevant mostly as a synchronous (online) events and thus are not recorded as part of the transcript of the conversation. You cannot retrieve them with the `get async` mechanism and they do not have sequence.

Regarding the `sequence`, you may want to keep track in your app the `maxSequenceSeen`. Every time you get a message you can extract the sequence from the message and check if you have to update your `maxSequenceSeen`.
During the reconnection you should make sure that all of the sequences until `maxSequenceSeen` have been received and query for the messages accordingly. In this case you should ignore sequences that you have already got.
