### ISSUE TITLE
Query to get messages user missed while being disconnected

### ISSUE THREAD

**Issue by eriesenfeld** [lp-docs-org/link-to-docs#2]
When I make a query call to get the messages the user missed while being disconnected, I receive extra 2 messages ‘ACCEPT’ and ‘READ’ (in addition to the text messages). See below.

Why are they needed ? These usually come-in as notification for user messages (not for Agent)

QUERYING CONTENT FROM LP :

{"kind":"req","id":"1","body":{"dialogId":"5ee21042-f7a4-47c2-98d1-a50df1fd9451","newerThanSequence":"5"},"type":".ams.ms.QueryMessages"}

QUERY RESULT: 

{"kind":"resp","reqId":"1","code":200,"body":[

{"sequence":5,"originatorClientProperties":{"type":".ClientProperties","deviceFamily":"DESKTOP","os":"OSX","osVersion":"10.11.6","browser":"CHROME","browserVersion":"53.0.2785.143"},"originatorId":"8343084.482365510","originatorPId":"5fbee692-6e49-5f70-ad52-ad86448bb665","serverTimestamp":1475959781673,"event":{"type":"AcceptStatusEvent","status":"ACCEPT","sequenceList":[4]},"dialogId":"5ee21042-f7a4-47c2-98d1-a50df1fd9451"},

{"sequence":6,"originatorClientProperties":{"type":".ClientProperties","deviceFamily":"DESKTOP","os":"OSX","osVersion":"10.11.6","browser":"CHROME","browserVersion":"53.0.2785.143"},"originatorId":"8343084.482365510","originatorPId":"5fbee692-6e49-5f70-ad52-ad86448bb665","serverTimestamp":1475959791729,"event":{"type":"AcceptStatusEvent","status":"READ","sequenceList":[2,4]},"dialogId":"5ee21042-f7a4-47c2-98d1-a50df1fd9451"},

{"sequence":7,"originatorClientProperties":{"type":".ClientProperties","deviceFamily":"DESKTOP","os":"OSX","osVersion":"10.11.6","browser":"CHROME","browserVersion":"53.0.2785.143"},"originatorId":"8343084.482365510","originatorPId":"5fbee692-6e49-5f70-ad52-ad86448bb665","serverTimestamp":1475959794858,"event":{"type":"ContentEvent","message":"111","contentType":"text/plain"},"dialogId":"5ee21042-f7a4-47c2-98d1-a50df1fd9451"},

{"sequence":8,"originatorClientProperties":{"type":".ClientProperties","deviceFamily":"DESKTOP","os":"OSX","osVersion":"10.11.6","browser":"CHROME","browserVersion":"53.0.2785.143"},"originatorId":"8343084.482365510","originatorPId":"5fbee692-6e49-5f70-ad52-ad86448bb665","serverTimestamp":1475959796403,"event":{"type":"ContentEvent","message":"222","contentType":"text/plain"},"dialogId":"5ee21042-f7a4-47c2-98d1-a50df1fd9451"},

{"sequence":9,"originatorClientProperties":{"type":".ClientProperties","deviceFamily":"DESKTOP","os":"OSX","osVersion":"10.11.6","browser":"CHROME","browserVersion":"53.0.2785.143"},"originatorId":"8343084.482365510","originatorPId":"5fbee692-6e49-5f70-ad52-ad86448bb665","serverTimestamp":1475959798324,"event":{"type":"ContentEvent","message":"333","contentType":"text/plain"},"dialogId":"5ee21042-f7a4-47c2-98d1-a50df1fd9451"},

{"sequence":10,"originatorClientProperties":{"type":".ClientProperties","deviceFamily":"DESKTOP","os":"OSX","osVersion":"10.11.6","browser":"CHROME","browserVersion":"53.0.2785.143"},"originatorId":"8343084.482365510","originatorPId":"5fbee692-6e49-5f70-ad52-ad86448bb665","serverTimestamp":1475959799676,"event":{"type":"ContentEvent","message":"444","contentType":"text/plain"},"dialogId":"5ee21042-f7a4-47c2-98d1-a50df1fd9451"},

{"sequence":11,"originatorClientProperties":{"type":".ClientProperties","deviceFamily":"DESKTOP","os":"OSX","osVersion":"10.11.6","browser":"CHROME","browserVersion":"53.0.2785.143"},"originatorId":"8343084.482365510","originatorPId":"5fbee692-6e49-5f70-ad52-ad86448bb665","serverTimestamp":1475959801211,"event":{"type":"ContentEvent","message":"555","contentType":"text/plain"},"dialogId":"5ee21042-f7a4-47c2-98d1-a50df1fd9451"}],"type":".ams.ms.QueryMessages$Response"}

**Comment by eitan101** [comment]
Sequences 5,6 were sent by the agent to confirm acceptance and read of the consumer messages (sequences 2,4).
You can read more about the read/accept receipts in [the tutorial](http://ec2-54-175-164-201.compute-1.amazonaws.com:4180/consumer-int-readaccept-events.html)
